# Generated by Django 3.2.2 on 2023-07-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершается в '),
        ),
    ]
