# Generated by Django 3.2.2 on 2023-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_event_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
