# Generated by Django 3.2.2 on 2023-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='рейтинг'),
        ),
    ]
