apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 36000
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          containers:
          - name: clearsessions
            image: fchef/k8s_django:latest
            env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: secret_key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: database_url
            envFrom:
            - configMapRef:
                name: django-config
            command:
            - python
            - manage.py
            - clearsessions
          restartPolicy: OnFailure
